### ISSUE TITLE
Production frequent crash: CursorAllocationException

### ISSUE THREAD

**Issue by KumarArab** [apxor/apxor-flutter-sdk#1]
### Source: Firebase

Not able to replicate it on dev environment, but lots of users are facing frequent crashes

### Crash Log
```dart
Fatal Exception: android.database.CursorWindowAllocationException: Could not allocate CursorWindow '/data/user/0/in.fello.felloapp/databases/apx_user.db' of size 2097152 due to error -12.
       at android.database.CursorWindow.nativeCreate(CursorWindow.java)
       at android.database.CursorWindow.<init>(CursorWindow.java:139)
       at android.database.CursorWindow.<init>(CursorWindow.java:120)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:202)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
       at com.apxor.androidsdk.core.datahandler.databases.ApxorBaseSQLiteWrapper.incrementCountAndUpsertData(ApxorBaseSQLiteWrapper.java:37)
       at com.apxor.androidsdk.core.datahandler.databases.c.a(c.java:74)
       at com.apxor.androidsdk.core.d.b.run(b.java:57)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

According to [StackOverflow](https://stackoverflow.com/questions/17495713/could-not-allocate-cursorwindow),  error -12 is because of cursor leak.

**Comment by PrasannaKumarReddi** [comment]
## Root Cause
 - Crash is observed in android 10 and android 11 devices causing CursorWindowAllocationException.
 -  Generally when enough memory to allocate for cursors is not present in a device  or cursors are not closed ( memory leak) it throws a CursorWindowAllocationException . But in Android 10 and Android 11 the exception is being thrown erroneously even there is no memory leak or memory shortage ( refer: https://issuetracker.google.com/issues/170228126 ).
## Prevention:
- Update the Apxor core plugin to version 2.8.7, which has the fix to handle this scenario.

Hope this helps.
